<?php

namespace DoctrineProxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class BBMBallparkProxy extends \BBM\Ballpark implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function __toString()
    {
        $this->_load();
        return parent::__toString();
    }

    public function setId($value)
    {
        $this->_load();
        return parent::setId($value);
    }

    public function setName($value)
    {
        $this->_load();
        return parent::setName($value);
    }

    public function setNickname($value)
    {
        $this->_load();
        return parent::setNickname($value);
    }

    public function setCity($value)
    {
        $this->_load();
        return parent::setCity($value);
    }

    public function setState($value)
    {
        $this->_load();
        return parent::setState($value);
    }

    public function setDateOpen($value)
    {
        $this->_load();
        return parent::setDateOpen($value);
    }

    public function setDateClose($value)
    {
        $this->_load();
        return parent::setDateClose($value);
    }

    public function setLeague($value)
    {
        $this->_load();
        return parent::setLeague($value);
    }

    public function setNotes($value)
    {
        $this->_load();
        return parent::setNotes($value);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'ballpark_id', 'name', 'nickname', 'city', 'state', 'dateopen', 'dateclose', 'league', 'notes', 'games');
    }
}