<?php

namespace DoctrineProxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class BBMPlayProxy extends \BBM\Play implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function __toString()
    {
        $this->_load();
        return parent::__toString();
    }

    public function setTeam(\BBM\Team $team)
    {
        $this->_load();
        return parent::setTeam($team);
    }

    public function getTeam()
    {
        $this->_load();
        return parent::getTeam();
    }

    public function setInning($value)
    {
        $this->_load();
        return parent::setInning($value);
    }

    public function setGame(\BBM\Game $game)
    {
        $this->_load();
        return parent::setGame($game);
    }

    public function getGame()
    {
        $this->_load();
        return parent::getGame();
    }

    public function setBatter(\BBM\Player $batter)
    {
        $this->_load();
        return parent::setBatter($batter);
    }

    public function getBatter()
    {
        $this->_load();
        return parent::getBatter();
    }

    public function setPitcher(\BBM\Player $pitcher)
    {
        $this->_load();
        return parent::setPitcher($pitcher);
    }

    public function getPitcher()
    {
        $this->_load();
        return parent::getPitcher();
    }

    public function setPitchCount($value)
    {
        $this->_load();
        return parent::setPitchCount($value);
    }

    public function setPitches($value)
    {
        $this->_load();
        return parent::setPitches($value);
    }

    public function setEvent($value)
    {
        $this->_load();
        return parent::setEvent($value);
    }

    public function getEvent()
    {
        $this->_load();
        return parent::getEvent();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'play_id', 'game', 'inning', 'team', 'batter', 'pitcher', 'pitchCount', 'pitches', 'event');
    }
}