<?php

namespace DoctrineProxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class BBMTeamProxy extends \BBM\Team implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function getDivision()
    {
        $this->_load();
        return parent::getDivision();
    }

    public function setDivision($division)
    {
        $this->_load();
        return parent::setDivision($division);
    }

    public function setLeague($league)
    {
        $this->_load();
        return parent::setLeague($league);
    }

    public function setAbbr($abbr)
    {
        $this->_load();
        return parent::setAbbr($abbr);
    }

    public function setNickname($value)
    {
        $this->_load();
        return parent::setNickname($value);
    }

    public function setAddress($city, $state, $zip)
    {
        $this->_load();
        return parent::setAddress($city, $state, $zip);
    }

    public function setCity($value)
    {
        $this->_load();
        return parent::setCity($value);
    }

    public function setTeamName($teamName)
    {
        $this->_load();
        return parent::setTeamName($teamName);
    }

    public function __toString()
    {
        $this->_load();
        return parent::__toString();
    }

    public function getGames()
    {
        $this->_load();
        return parent::getGames();
    }

    public function addGame(\BBM\Game $game)
    {
        $this->_load();
        return parent::addGame($game);
    }

    public function setStartingLineup(\BBM\StartingLineup $lineup)
    {
        $this->_load();
        return parent::setStartingLineup($lineup);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'abbr', 'nickname', 'league', 'division', 'city', 'state', 'zip', 'homeGames', 'awayGames', 'plays');
    }
}